[package]
name = "desmos_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
inkwell = { version = "0.5.0", features = ["llvm18-0", "llvm18-0-prefer-dynamic"] }
lazy_static = "1.5.0"
pest = "2.7.11"
pest_derive = "2.7.11"
thiserror = "1.0.63"
